#!/usr/bin/env bash

PACKAGE_MANAGER="brew"

command -v gcc-8 >/dev/null 2>&1 || {
    echo -e >&2 "${YELLOW}gcc-8 ${RED}is required but not found${NC}"
    echo -e >&2 "${BLUE}... installing ${YELLOW}gcc-8${BLUE} ... ${NC}\n"
    ${PACKAGE_MANAGER} install gcc
    echo -e >&2 ""
}

command -v g++-8 >/dev/null 2>&1 || {
    echo -e >&2 "${YELLOW}g++-8 ${RED}is required but not found${NC}"
    echo -e >&2 "${BLUE}... installing ${YELLOW}g++-8${BLUE} ... ${NC}\n"
    ${PACKAGE_MANAGER} install gcc
    echo -e >&2 ""
}

command -v flex >/dev/null 2>&1 || {
    echo -e >&2 "${YELLOW}flex ${RED}is required but not found${NC}"
    echo -e >&2 "${BLUE}... installing ${YELLOW}flex${BLUE} ... ${NC}\n"
    ${PACKAGE_MANAGER} install flex
    echo -e >&2 ""
}

command -v bison >/dev/null 2>&1 || {
    echo -e >&2 "${YELLOW}bison ${RED}is required but not found${NC}"
    echo -e >&2 "${BLUE}... installing ${YELLOW}bison${BLUE} ... ${NC}\n"
    ${PACKAGE_MANAGER} install bison
    echo -e >&2 ""
}

command -v tree >/dev/null 2>&1 || {
    echo -e >&2 "${YELLOW}tree ${RED}is required but not found${NC}"
    echo -e >&2 "${BLUE}... installing ${YELLOW}tree${BLUE} ... ${NC}\n"
    ${PACKAGE_MANAGER} install tree
    echo -e >&2 ""
}

export CC=$(command -v gcc-8)
export CPP=$(command -v g++-8)
export FLEX=$(command -v flex)
export BISON=$(command -v bison)
export TREE=$(command -v tree)
