#!/usr/bin/env bash

PACKAGE_MANAGER="brew"

command -v gcc-8 >/dev/null 2>&1 || { echo >&2 "gcc-8 is being installed"; ${PACKAGE_MANAGER} install build-essential; }
command -v g++-8 >/dev/null 2>&1 || { echo >&2 "g++-8 is being installed"; ${PACKAGE_MANAGER} install build-essential; }
command -v flex  >/dev/null 2>&1 || { echo >&2 "flex is being installed";  ${PACKAGE_MANAGER} install flex;            }
command -v bison >/dev/null 2>&1 || { echo >&2 "bison is being installed"; ${PACKAGE_MANAGER} install bison;           }
command -v tree  >/dev/null 2>&1 || { echo >&2 "tree is being installed";  ${PACKAGE_MANAGER} install tree;            }

CC=$(command -v gcc-8)
CPP=$(command -v g++-8)
FLEX=$(command -v flex)
BISON=$(command -v bison)
TREE=$(command -v tree)

echo "gcc-8 found at: ${CC}"
echo "g++-8 found at: ${CPP}"
echo "flex found at: ${FLEX}"
echo "bison found at: ${BISON}"
echo "tree found at: ${TREE}"

echo -e "\
CC := ${CC}\n\
CPP := ${CPP}\n\
FLEX := ${FLEX}\n\
BISON := ${BISON}\n\
TREE := ${TREE}\n\
" > tools
