# macros

TARGET := fs-make
VERSION := 1.0.0
DEFINES := -D TARGET=\"$(TARGET)\" -D VERSION=\"$(VERSION)\"

# files

BIN := /usr/local/bin

YFILES := $(wildcard *.y)

TABFILES := \
	$(YFILES:.y=.tab.c) \
	$(YFILES:.y=.tab.h)

YYFILES := lex.yy.c

CFILES := \
	$(wildcard *.c) \
	$(YFILES:.y=.tab.c) \
	$(YYFILES)

CPPFILES := $(wildcard *.cpp)

OBJECTS := \
	$(CFILES:.c=.o) \
	$(CPPFILES:.cpp=.o)

DEPS := $(OBJECTS:.o=.d)

.PHONY := all clean install uninstall

# colours

PRE := \033[

NC := $(PRE)0m
GREEN := $(PRE)1;32m
YELLOW := $(PRE)1;33m
BLUE := $(PRE)1;36m
RED := $(PRE)1;31m

# tools

# generated by the configure script
-include tools

RM := rm
IN := install

# flags

CFLAGS := $(DEFINES) -Wall -Wextra -Wpedantic -g -MMD -MP -c
FLEXFLAGS := 
BISONFLAGS := -d
RMFLAGS := -f
INFLAGS := 
TREEFLAGS := -a

# make

all: $(TARGET)
	@echo "$(GREEN)Build complete!$(NC)"

uninstall:
	@echo "$(RED)Uninstalling $(TARGET)$(NC)"
	sudo $(RM) $(RMFLAGS) $(BIN)/$(TARGET)

install:
	@echo "$(GREEN)Installing $(TARGET)$(NC)"
	sudo $(IN) $(INFLAGS) $(TARGET) $(BIN)/$(TARGET)

$(TARGET): $(OBJECTS)
	@echo "$(YELLOW)Making $@$(NC)"
	$(CPP) -o $(TARGET) $^

%.o: %.c
	@echo "$(BLUE)Making $@$(NC)"
	$(CC) $(CFLAGS) $<

%.o: %.cpp
	@echo "$(BLUE)Making $@$(NC)"
	$(CPP) $(CFLAGS) $<

lex.yy.c: lexer.l
	@echo "$(BLUE)Making $@$(NC)"
	$(FLEX) $(FLEXFLAGS) $<

grammar.tab.c grammar.tab.h: grammar.y
	@echo "$(BLUE)Making grammar.tab.c and grammar.tab.h$(NC)"
	$(BISON) $(BISONFLAGS) $<

clean:
	@echo "$(RED)Cleaning$(NC)"
	$(RM) $(RMFLAGS) $(OBJECTS) $(DEPS) $(YYFILES) $(TABFILES) $(TARGET)

# from generated dependency files

-include $(DEPS)
