# meta

TARGET := fs-make
VERSION := 1.0.0

# files

BIN := /usr/local/bin

YFILES := $(wildcard *.y)

TABFILES := \
	$(YFILES:.y=.tab.c) \
	$(YFILES:.y=.tab.h)

YYFILES := lex.yy.c

CFILES := \
	$(wildcard *.c) \
	$(YFILES:.y=.tab.c) \
	$(YYFILES)

CPPFILES := $(wildcard *.cpp)

OBJECTS := \
	$(CFILES:.c=.o) \
	$(CPPFILES:.cpp=.o)

DEPS := $(OBJECTS:.o=.d)

.PHONY := all clean install uninstall

# colours

PRE := \033[

NC := $(PRE)0m
GREEN := $(PRE)1;32m
YELLOW := $(PRE)1;33m
BLUE := $(PRE)1;36m
RED := $(PRE)1;31m

# tools

# generated by the configure script
-include tools

RM := rm
IN := install

# flags

DEFINES := -D TARGET=\"$(TARGET)\" -D VERSION=\"$(VERSION)\"

CFLAGS := $(DEFINES) -Wall -Wextra -Wpedantic -g -MMD -MP -c
FLEXFLAGS := 
BISONFLAGS := -d
RMFLAGS := -f
INFLAGS := 
TREEFLAGS := -a

# recipes

all: $(TARGET)
	@echo "$(GREEN)Build complete!$(NC)\n"
	@echo "$(BLUE)Now, install $(YELLOW)$(TARGET)$(BLUE) with: $(YELLOW)make install$(NC)"

uninstall:
	@echo "$(RED)... uninstalling $(YELLOW)$(TARGET)$(RED) ...$(NC)\n"
	sudo $(RM) $(RMFLAGS) $(BIN)/$(TARGET)
	@echo ""
	@echo "$(RED)Uninstallation complete. :($(NC)\n"
	@echo "$(BLUE)Now, install $(YELLOW)$(TARGET)$(BLUE) with: $(YELLOW)make install$(NC)"

install:
	@echo "$(GREEN)... installing $(YELLOW)$(TARGET)$(GREEN) ...$(NC)\n"
	sudo $(IN) $(INFLAGS) $(TARGET) $(BIN)/$(TARGET)
	@echo ""
	@echo "$(GREEN)Installation complete!$(NC)\n"
	@echo "$(BLUE)Now, you may run $(YELLOW)$(TARGET)$(BLUE) with: $(YELLOW)$(TARGET)$(NC)"

$(TARGET): $(OBJECTS)
	@echo "$(BLUE)... making $(YELLOW)$@ $(BLUE)...$(NC)\n"
	$(CPP) -o $(TARGET) $^
	@echo ""

%.o: %.c
	@echo "$(BLUE)... making $(YELLOW)$@ $(BLUE)...$(NC)\n"
	$(CC) $(CFLAGS) $<
	@echo ""

%.o: %.cpp
	@echo "$(BLUE)... making $(YELLOW)$@ $(BLUE)...$(NC)\n"
	$(CPP) $(CFLAGS) $<
	@echo ""

lex.yy.c: lexer.l
	@echo "$(BLUE)... making $(YELLOW)$@ $(BLUE)...$(NC)\n"
	$(FLEX) $(FLEXFLAGS) $<
	@echo ""

grammar.tab.c grammar.tab.h: grammar.y
	@echo "$(BLUE)... making $(YELLOW)grammar.tab.c $(BLUE)and $(YELLOW)grammar.tab.h $(BLUE)...$(NC)\n"
	$(BISON) $(BISONFLAGS) $<
	@echo ""

clean:
	@echo "$(RED)... cleaning up ...$(NC)\n"
	$(RM) $(RMFLAGS) $(OBJECTS) $(DEPS) $(YYFILES) $(TABFILES) $(TARGET)

# from the generated dependency files

-include $(DEPS)
