name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Running on sample.json
      run: |
        cd ./tests
        ../fsmake sample.json out-sample.sh
        mkdir root
        cd root
        bash ../out-sample.sh
