name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Install
      run: make install
    - name: Running on sample.json
      run: |
        cd ./tests
        fs-make sample.json out-sample.sh
        . ./out-sample.sh
        tree -a project
    - name: Clean
      run: make clean
    - name: Uninstall
      run: make uninstall
