name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt install flex bison
    - name: Build
      run: make
    - name: Running on sample.json
      run: |
        cd ./tests
        fs-make sample.json out-sample.sh
        mkdir root
        cd root
        bash ../out-sample.sh
        tree
